version: '3.8'
services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file: ./apps/api/.env

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: ./apps/web/.env
    depends_on:
      - api