import { BADGE_SLUGS } from '../../src/badges/badges.constants';
import type { BadgeSeed } from '../../src/badges/types/criteria';

/**
 * Source of truth for the badge catalog. Order matches the design
 * document (tier-grouped). Every slug here must have a matching SVG at
 * `apps/web/public/badges/icons/<slug>.svg`.
 *
 * `criteria.type === 'deferred'` means the catalog row will be created
 * but no strategy will auto-award it — those badges depend on a stable
 * shape for `Review.feedback` (security flags, coverage delta, complexity
 * delta, etc.) that is not yet defined.
 */
export const BADGE_CATALOG: readonly BadgeSeed[] = [
  // ───── Contributor tier ─────
  {
    slug: BADGE_SLUGS.FIRST_PR_LANDED,
    name: 'Hello, World',
    role: 'First-Time Contributor',
    description:
      'Submitted your very first pull request for AI review. The journey starts here.',
    iconKey: BADGE_SLUGS.FIRST_PR_LANDED,
    tier: 'contributor',
    category: 'activity',
    rarity: 'common',
    colorTheme: 'blue',
    xpReward: 50,
    visibleOnPrComment: true,
    progressTrackable: false,
    progressLabel: 'Earned on first PR',
    criteria: { type: 'milestone', event: 'first_pr_reviewed' },
  },
  {
    slug: BADGE_SLUGS.STREAK_STARTER,
    name: 'Streak Starter',
    role: 'Daily Shipper',
    description:
      'Shipped a reviewed PR every day for seven consecutive days. The habit is forming.',
    iconKey: BADGE_SLUGS.STREAK_STARTER,
    tier: 'contributor',
    category: 'streak',
    rarity: 'common',
    colorTheme: 'amber',
    xpReward: 100,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 7 day streak',
    criteria: { type: 'streak', metric: 'active_days', value: 7 },
  },
  {
    slug: BADGE_SLUGS.MONTHLY_GRINDER,
    name: 'Monthly Grinder',
    role: '30-Day Devotee',
    description:
      'A full thirty days of consecutive reviewed PRs. This is no longer a habit — it’s identity.',
    iconKey: BADGE_SLUGS.MONTHLY_GRINDER,
    tier: 'contributor',
    category: 'streak',
    rarity: 'uncommon',
    colorTheme: 'teal',
    xpReward: 250,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 30 day streak',
    criteria: { type: 'streak', metric: 'active_days', value: 30 },
  },
  {
    slug: BADGE_SLUGS.ACTIVE_CONTRIBUTOR,
    name: 'Active Contributor',
    role: 'Cadence Keeper',
    description:
      'Twenty-five reviewed PRs in a rolling 30-day window. You ship reliably.',
    iconKey: BADGE_SLUGS.ACTIVE_CONTRIBUTOR,
    tier: 'contributor',
    category: 'activity',
    rarity: 'uncommon',
    colorTheme: 'blue',
    xpReward: 200,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 25 PRs in last 30d',
    criteria: {
      type: 'count_in_rolling_window',
      metric: 'reviews',
      value: 25,
      windowDays: 30,
    },
  },
  {
    slug: BADGE_SLUGS.COMEBACK_KID,
    name: 'Comeback Kid',
    role: 'Returning Champion',
    description:
      'Returned after thirty-plus days of silence and shipped within a week. Welcome back.',
    iconKey: BADGE_SLUGS.COMEBACK_KID,
    tier: 'contributor',
    category: 'activity',
    rarity: 'uncommon',
    colorTheme: 'coral',
    xpReward: 150,
    visibleOnPrComment: false,
    progressTrackable: false,
    progressLabel: 'One-time milestone',
    criteria: {
      type: 'deferred',
      reason: 'gap-then-return predicate; needs design pass',
    },
  },

  // ───── Quality tier ─────
  {
    slug: BADGE_SLUGS.CLEAN_REVIEW,
    name: 'Clean Review',
    role: 'Pristine Coder',
    description:
      'Shipped a single PR with an AI quality score of 95 or higher. One perfect deliverable.',
    iconKey: BADGE_SLUGS.CLEAN_REVIEW,
    tier: 'quality',
    category: 'code_quality',
    rarity: 'common',
    colorTheme: 'green',
    xpReward: 100,
    visibleOnPrComment: true,
    progressTrackable: false,
    progressLabel: 'Earned on qualifying PR',
    criteria: {
      type: 'count',
      metric: 'reviews',
      value: 1,
      filters: { minScore: 95 },
    },
  },
  {
    slug: BADGE_SLUGS.ZERO_ISSUE_AUTHOR,
    name: 'Zero-Issue Author',
    role: 'Flawless Streaker',
    description:
      'Five consecutive PRs with zero AI-flagged issues across all categories. Dialed in.',
    iconKey: BADGE_SLUGS.ZERO_ISSUE_AUTHOR,
    tier: 'quality',
    category: 'code_quality',
    rarity: 'uncommon',
    colorTheme: 'green',
    xpReward: 300,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 5 flawless PRs in a row',
    criteria: {
      type: 'deferred',
      reason: 'needs Review.feedback flag-count shape',
    },
  },
  {
    slug: BADGE_SLUGS.SECURITY_FIRST,
    name: 'Security First',
    role: 'Vulnerability Closer',
    description:
      'Resolved ten security flags raised by the AI reviewer. The codebase is safer for it.',
    iconKey: BADGE_SLUGS.SECURITY_FIRST,
    tier: 'quality',
    category: 'security',
    rarity: 'uncommon',
    colorTheme: 'purple',
    xpReward: 250,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 10 security flags resolved',
    criteria: {
      type: 'deferred',
      reason: 'needs Review.feedback security-flag shape',
    },
  },
  {
    slug: BADGE_SLUGS.VULNERABILITY_HUNTER,
    name: 'Vulnerability Hunter',
    role: 'Security Sentinel',
    description:
      'Resolved fifty security flags lifetime, with zero criticals in your last fifty PRs.',
    iconKey: BADGE_SLUGS.VULNERABILITY_HUNTER,
    tier: 'quality',
    category: 'security',
    rarity: 'rare',
    colorTheme: 'purple',
    xpReward: 600,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel:
      '{{current}} / 50 resolved · {{criticals}} criticals last 50 PRs',
    criteria: {
      type: 'deferred',
      reason: 'needs Review.feedback security-flag shape',
    },
  },
  {
    slug: BADGE_SLUGS.IMMACULATE_CODEBASE,
    name: 'Immaculate Codebase',
    role: 'Quality Architect',
    description:
      'Fifty PRs with an average AI quality score of 90 or above. Sustained, not lucky.',
    iconKey: BADGE_SLUGS.IMMACULATE_CODEBASE,
    tier: 'quality',
    category: 'code_quality',
    rarity: 'rare',
    colorTheme: 'green',
    xpReward: 500,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 50 PRs at avg {{avg}}',
    criteria: { type: 'lifetime_avg_score', minPrs: 50, minAvgScore: 90 },
  },

  // ───── Specialist tier ─────
  {
    slug: BADGE_SLUGS.TEST_FIRST_DEVELOPER,
    name: 'Test-First Developer',
    role: 'Coverage Crusader',
    description:
      'Twenty-five PRs that each pushed test coverage above 80%. Tests come first, ship comes second.',
    iconKey: BADGE_SLUGS.TEST_FIRST_DEVELOPER,
    tier: 'specialist',
    category: 'testing',
    rarity: 'uncommon',
    colorTheme: 'amber',
    xpReward: 350,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 25 coverage-positive PRs',
    criteria: {
      type: 'deferred',
      reason: 'needs Review.feedback coverage-delta shape',
    },
  },
  {
    slug: BADGE_SLUGS.COVERAGE_CHAMPION,
    name: 'Coverage Champion',
    role: 'Confidence Builder',
    description:
      'Lifetime coverage average of 85% or higher across at least 100 reviewed PRs.',
    iconKey: BADGE_SLUGS.COVERAGE_CHAMPION,
    tier: 'specialist',
    category: 'testing',
    rarity: 'rare',
    colorTheme: 'amber',
    xpReward: 600,
    visibleOnPrComment: false,
    progressTrackable: true,
    progressLabel: '{{current}} / 100 PRs · avg {{avg}}%',
    criteria: {
      type: 'deferred',
      reason: 'needs Review.feedback coverage-percent shape',
    },
  },
  {
    slug: BADGE_SLUGS.DOC_DEVOTEE,
    name: 'Doc Devotee',
    role: 'Knowledge Keeper',
    description:
      'Twenty-five PRs flagged "documentation complete" by the AI reviewer.',
    iconKey: BADGE_SLUGS.DOC_DEVOTEE,
    tier: 'specialist',
    category: 'documentation',
    rarity: 'uncommon',
    colorTheme: 'coral',
    xpReward: 300,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 25 documented PRs',
    criteria: {
      type: 'deferred',
      reason: 'needs Review.feedback docs-complete shape',
    },
  },
  {
    slug: BADGE_SLUGS.PERFORMANCE_OPTIMIZER,
    name: 'Performance Optimizer',
    role: 'Latency Slayer',
    description:
      'Twenty-five PRs delivered measurable performance wins. Speed compounds.',
    iconKey: BADGE_SLUGS.PERFORMANCE_OPTIMIZER,
    tier: 'specialist',
    category: 'performance',
    rarity: 'rare',
    colorTheme: 'pink',
    xpReward: 550,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 25 perf-positive PRs',
    criteria: {
      type: 'deferred',
      reason: 'needs Review.feedback perf-delta shape',
    },
  },
  {
    slug: BADGE_SLUGS.REFACTOR_ARTISAN,
    name: 'Refactor Artisan',
    role: 'Complexity Tamer',
    description:
      'Twenty-five PRs each cut complexity by ten points or more. Less code, better code.',
    iconKey: BADGE_SLUGS.REFACTOR_ARTISAN,
    tier: 'specialist',
    category: 'code_quality',
    rarity: 'rare',
    colorTheme: 'teal',
    xpReward: 500,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 25 complexity-cutting PRs',
    criteria: {
      type: 'deferred',
      reason: 'needs Review.feedback complexity-delta shape',
    },
  },

  // ───── Elite tier ─────
  {
    slug: BADGE_SLUGS.PLATFORM_PIONEER,
    name: 'Platform Pioneer',
    role: 'Day-One Believer',
    description:
      'Among the first one hundred users on the platform. The early days are yours by right.',
    iconKey: BADGE_SLUGS.PLATFORM_PIONEER,
    tier: 'elite',
    category: 'platform',
    rarity: 'legendary',
    colorTheme: 'amber',
    xpReward: 1000,
    visibleOnPrComment: false,
    progressTrackable: false,
    progressLabel: 'Awarded automatically at signup',
    criteria: { type: 'signup_rank', maxRank: 100 },
  },
  {
    slug: BADGE_SLUGS.KILOCODER,
    name: 'Kilocoder',
    role: 'Volume Virtuoso',
    description: 'One thousand reviewed PRs lifetime. Few enter this room.',
    iconKey: BADGE_SLUGS.KILOCODER,
    tier: 'elite',
    category: 'activity',
    rarity: 'legendary',
    colorTheme: 'purple',
    xpReward: 2000,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 1000 PRs',
    criteria: { type: 'count', metric: 'reviews', value: 1000 },
  },
  {
    slug: BADGE_SLUGS.FLAWLESS_YEAR,
    name: 'Flawless Year',
    role: '365-Day Sovereign',
    description:
      'Three hundred and sixty-five consecutive days. A full revolution. Unbroken.',
    iconKey: BADGE_SLUGS.FLAWLESS_YEAR,
    tier: 'elite',
    category: 'streak',
    rarity: 'legendary',
    colorTheme: 'red',
    xpReward: 2500,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 365 day streak',
    criteria: { type: 'streak', metric: 'active_days', value: 365 },
  },
  {
    slug: BADGE_SLUGS.POLYGLOT_MASTER,
    name: 'Polyglot Master',
    role: 'Cross-Language Sage',
    description:
      'Five languages, each with an average AI score of 85+ across 50+ PRs. Mastery without borders.',
    iconKey: BADGE_SLUGS.POLYGLOT_MASTER,
    tier: 'elite',
    category: 'code_quality',
    rarity: 'legendary',
    colorTheme: 'teal',
    xpReward: 1500,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 5 mastered languages',
    criteria: {
      type: 'polyglot',
      minLanguages: 5,
      minPrsPerLanguage: 50,
      minAvgScorePerLanguage: 85,
    },
  },
  {
    slug: BADGE_SLUGS.CODELENS_LEGEND,
    name: 'Codelens Legend',
    role: 'Hall of Fame',
    description:
      'Earned at least fifteen badges across every category. The full set. The legend grade.',
    iconKey: BADGE_SLUGS.CODELENS_LEGEND,
    tier: 'elite',
    category: 'platform',
    rarity: 'legendary',
    colorTheme: 'amber',
    xpReward: 2500,
    visibleOnPrComment: true,
    progressTrackable: true,
    progressLabel: '{{current}} / 15 badges across all categories',
    criteria: { type: 'badge_count_self', minBadges: 15 },
  },
];
